core/urls.py
from django.contrib import admin
from django.urls import path, include
from main import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("__reload__/", include("django_browser_reload.urls")),
    #own apps
    path('', include('main.urls')),
    path('', include('workspace.urls')),
    path('', include('controlpanel.urls'))
]

handler404 = 'main.views.page_not_found_view'

workspace/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth.models import Group, Permission
from django.core.validators import URLValidator, MinValueValidator
from django.core.exceptions import ValidationError
from django.db.models import Max
from datetime import date

 #Opciones
MODALIDAD_SELECCION_CHOICES = [
        ('Sin Clasificar', 'Sin Clasificar'),
        ('Directa', 'Directa'),
        ('Privada', 'Privada'),
        ('Publica', 'Publica'),
    ]
CLASE_CONTRATO_CHOICES = [
        ('Arrendamiento', 'Arrendamiento'),
        ('Cesión Derechos Patrimoniales', 'Cesión Derechos Patrimoniales'),
        ('Compraventa', 'Compraventa'),
        ('Consultoría', 'Consultoría'),
        ('Interadministrativo', 'Interadministrativo'),
        ('Obra Pública', 'Obra Pública'),
        ('Orden Compra Colombia Compra Eficiente', 'Orden Compra Colombia Compra Eficiente'),
        ('Prestación de Servicios', 'Prestación de Servicios'),
        ('Prestación de Servicios y Compraventa', 'Prestación de Servicios y Compraventa'),
        ('Prestación de Servicios y Suministro', 'Prestación de Servicios y Suministro'),
        ('Seguros', 'Seguros'),
        ('Prestación de Servicios Profesionales', 'Prestación de Servicios Profesionales'),
        ('Suministro', 'Suministro'),
    ]
FUENTE_RECURSOS_CHOICES = [('Recursos propios', 'Recursos propios'),
        ('Presupuesto de entidad nacional', 'Presupuesto de entidad nacional'),
        ('Regalías', 'Regalías'),
        ('Recursos de credito', 'Recursos de credito'),
        ('SGP', 'SGP'),
        ('No Aplica', 'No Aplica'),
    ]
ESTADO_CONTRATO_CHOICES = [
        ('Activo', 'Activo'),
        ('Suspendido', 'Suspendido'),
        ('Liquidado', 'Liquidado'),
    ]


class Contratista(models.Model):
    nombre = models.CharField(max_length=255, blank=False, unique=True)
    nit_o_cc = models.IntegerField(blank=True, null=True)
    representante_legal = models.CharField(max_length=255, blank=True, null=True)
    nit_o_cc_representante_legal = models.IntegerField(blank=True, null=True)
    telefono = models.CharField(max_length=20, blank=True, null=True)
    email = models.EmailField(blank=True, null=True)
    email_secundario = models.EmailField(blank=True, null=True)
    consorcio = models.CharField(max_length=255, blank= True, null = True )
    #extra
    fecha_agregado = models.DateField(auto_now_add=True, null=True)

    def __str__(self):
        return self.nombre

class Supervisor(models.Model):
    nombre = models.CharField(max_length=255)
    nit_o_cc = models.IntegerField()
    cargo = models.CharField(max_length=255, blank=True, null=True)
    telefono = models.CharField(max_length=20, blank=True, null=True)
    email = models.EmailField(blank=True, null=True)
    #extra
    fecha_agregado = models.DateField(blank=True, null=True)

    def __str__(self):
        return self.nombre

class Rol(models.Model):
    USUARIO_ROLES = (
        ('gestor', 'Gestor'),
        ('abogado', 'Abogado'),
        ('revisor', 'Revisor'),
    )

    usuario = models.ForeignKey(User, on_delete=models.CASCADE, related_name='roles')
    rol = models.CharField(max_length=10, choices=USUARIO_ROLES)
    grupo = models.ForeignKey(Group, on_delete=models.SET_NULL, null=True, blank=True)
    permisos_adicionales = models.ManyToManyField(Permission, blank=True)

    class Meta:
        unique_together = ('usuario', 'rol')

    def __str__(self):
        return f"{self.usuario.username} ({self.get_rol_display()})"



# INICIO DE LO RELACIONADO CON CONTRATO ===========================================================================================================

#TODO: revisar todos lso modelos en su integracion
# Estas con las que puede coexistir con el proceso de manera activa
class Adicion(models.Model):
    contrato = models.ForeignKey('Contrato', on_delete=models.CASCADE, related_name='adiciones', null=True)
    adicion_1 = models.CharField(max_length=255)
    adicion_2 = models.CharField(max_length=255, blank=True, null=True)
    adicion_3 = models.CharField(max_length=255, blank=True, null=True)
    valor_total = models.DecimalField(max_digits=20, decimal_places=2)
    #extra
    fecha = models.DateField()

class Prorroga(models.Model):
    contrato = models.ForeignKey('Contrato', on_delete=models.CASCADE, related_name='prorrogas', null=True)
    fecha = models.DateField(null=True)
    justificacion = models.TextField(null=True)
    nueva_fecha_terminacion = models.DateField(null=True)
    fecha_suspension = models.DateField(blank=True, null=True)
    fecha_reinicio = models.DateField(blank=True, null=True)
    

class Modificacion(models.Model):
    contrato = models.ForeignKey('Contrato', on_delete=models.CASCADE, related_name='modificaciones', null=True)
    fecha_subscripcion =  models.DateField(null=True)
    motivo =  models.CharField( max_length=250,null=True)

class Aclaracion(models.Model):
    contrato = models.ForeignKey('Contrato', on_delete=models.CASCADE, related_name='aclaraciones', null=True)
    fecha_subscripcion =  models.DateField(null=True)
    motivo =  models.CharField( max_length=250,null=True)

# Estas con las que NO puede coexistir con el proceso de manera activa

class Suspension(models.Model):
    contrato = models.ForeignKey('Contrato', on_delete=models.CASCADE, related_name='suspensiones', null=True)
    fecha_subscripcion =  models.DateField(null=True)
    plazo= models.DateField(null=True)
    fecha_posible_reinicio =  models.DateField(blank = True, null = True)

class Reinicio(models.Model):
    contrato = models.ForeignKey('Contrato', on_delete=models.CASCADE, related_name='reinicios', null=True)
    fecha_subscripcion =  models.DateField(null=True)
    fecha_terminacion = models.DateField(null=True)

class Ampliacion(models.Model):
    contrato = models.ForeignKey('Contrato', on_delete=models.CASCADE, related_name='ampliaciones', null=True)
    fecha_subscripcion =  models.DateField(null=True)
    fecha_terminacion = models.DateField(null=True)


# CONTRATO ===========================================================================================================

class Contrato(models.Model):
    

    #Datos Generales
    objeto = models.TextField(blank=True, null=True, default="no se ha presentado objeto")
    numero_contrato = models.IntegerField(unique=True, blank=True, null=True, default=0)
    tipo_contratacion = models.CharField(max_length=600, choices=MODALIDAD_SELECCION_CHOICES, default="Sin Tipo")
    clase = models.CharField(max_length=600, choices=CLASE_CONTRATO_CHOICES, blank=True, null=True, default="Sin Clase")
    valor = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True, default=0)  # final
    plazo = models.CharField(max_length=50 , blank= True, null = True)
    fecha_suscripcion_contrato = models.DateField(blank=True, null=True)
    #Contractual ----------------------------------------------------------------------------------------------------------------------------
    # CDP y RP
    CDP_num = models.IntegerField(unique=True, blank=True, null=True)
    CDP_fecha = models.DateField(blank=True, null=True)
    RP_num = models.IntegerField(unique=True, blank=True, null=True)
    RP_fecha = models.DateField(blank=True, null=True)
    #Rubro Presupuestal
    rubro_presupuestal = models.CharField(blank=True,null=True, max_length=500)
    # polizas
    numero_poliza = models.PositiveIntegerField(
        blank=True,
        null=True,  
        validators=[MinValueValidator(0, message="El número de póliza debe ser un entero positivo.")],
        default=0
    )
    fecha_poliza_expedicion = models.DateField(blank=True, null=True)
    fecha_poliza_aprobacion = models.DateField(blank=True, null=True)
    aseguradora = models.CharField(blank=True, null=True, max_length=50)
    #fuente de recursos
    fuente_recursos = models.CharField(
        max_length=600, 
        choices=FUENTE_RECURSOS_CHOICES, 
        blank=True, 
        null=True
    )  # SIGEP
    # plazos 
    plazo_inicio = models.DateField(blank=True, null=True)
    plazo_fin = models.DateField(blank=True, null=True)
    #estados
    estado_contrato=models.CharField(default='Activo' , max_length=200, choices=ESTADO_CONTRATO_CHOICES)
    #documentos
    documentos_cargados = models.URLField(max_length=600, blank=True, null=True)
    #Secop
    fecha_publicacion_secop = models.DateField(blank=True, null=True, default="www.unillanos.edu.co")
    publicacion_secop = models.URLField(
        max_length=600, 
        blank=True,
        null=True,
    )
    #Almacen
    almacen = models.BooleanField(default=False)
    fecha_liquidacion = models.DateField(blank=True, null=True)

    #PAA ----------------------------------------------------------------------------------------------------------------------------------------
    dependencia_responsable = models.CharField(max_length=255, blank=True, null=True)
    ubicacion = models.CharField(max_length=600, blank=True, null=True)
    presupuesto_programado = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True) 
    modalidad_seleccion = models.CharField(max_length=600, blank=True, null=True)  

    
    # llaves foraneas ---------------------------------------------------------------------------------------------------------------------------
    # Extensiones del contrato si llega a suceder
    # gestores involucrados
    contratista = models.ForeignKey(Contratista, on_delete=models.SET_NULL, blank=True, null=True)
    supervisor = models.ForeignKey(Supervisor, on_delete=models.SET_NULL, blank=True, null=True)

    # Usuarios involucrados
    gestor = models.ForeignKey(User, related_name='gestor_contratos', on_delete=models.SET_NULL, null=True, blank=True)
    abogado = models.ForeignKey(User, related_name='abogado_contratos', on_delete=models.SET_NULL, null=True, blank=True)

theme/templates/personal/create_contratista.html
{% extends "dashboard.html" %}
{% load static tailwind_tags %}
{% load static %}
{% load form_filters %}
{% block title %} SCG - Crear Contratista {% endblock title %}
{% block contentdash %}

<section class="text-gray-600 body-font w-screen overflow-auto">
    <div class="container px-5 py-14 my-10 mx-auto bg-white shadow-lg rounded-lg">
        <div class="flex flex-col text-center w-full mb-10">
            <h1 class="sm:text-4xl text-3xl font-medium title-font mb-2 text-gray-900">Crear un nuevo contratista</h1>
            <p class="lg:w-2/3 mx-auto leading-relaxed text-base">Por favor, completa los detalles del contratista a continuación.</p>
        </div>

        {% if messages %}
            <div class="mb-6">
                <ul class="text-red-600">
                    {% for message in messages %}
                        <li>{{ message }}</li>
                    {% endfor %}
                </ul>
            </div>
        {% endif %}

        <form method="POST" class="w-full mx-auto">
            {% csrf_token %}
            <div class="flex flex-wrap -m-2">
                {% for field in form %}
                    <div class="p-2 w-full md:w-1/2">
                        <div class="relative">
                            <label for="{{ field.id_for_label }}" class="leading-7 text-sm text-gray-600">{{ field.label }}</label>
                            {{ field|add_class:"w-full bg-gray-100 bg-opacity-50 rounded border border-gray-300 focus:border-indigo-500 focus:bg-white focus:ring-2 focus:ring-indigo-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out" }}
                        </div>
                    </div>
                {% endfor %}
                
                <!-- Botones de Envío y Cancelar -->
                <div class="flex justify-end w-full items-end">
                    <div class="p-2 mt-4">
                        <a href="{% url 'sp' %}" class="flex ml-auto text-white bg-red-500 border-0 py-2 px-8 focus:outline-none hover:bg-red-600 rounded text-lg">Cancelar</a>
                    </div>
                    <div class="p-2 mt-4">
                        <button type="submit" class="flex ml-auto text-white bg-indigo-500 border-0 py-2 px-8 focus:outline-none hover:bg-indigo-600 rounded text-lg">Crear Contratista</button>
                    </div>
                </div>
            </div>            
        </form>
    </div>
</section>

{% endblock %}

{% block header %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
{% endblock header %}

{% block scripts %}
<script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
<script src="{% static "js/calendar.js" %}"></script>
{% endblock scripts %}

theme/templates/personal/create_contratista_pn.html
{% extends "dashboard.html" %}
{% load static tailwind_tags %}
{% load static %}
{% load form_filters %}
{% block title %} SCG - Crear Contratista {% endblock title %}
{% block contentdash %}

<section class="text-gray-600 body-font w-screen overflow-auto">
    <div class="container px-5 py-14 my-10  ml-10 max-w-[1400px] bg-white shadow-lg rounded-lg">
        <div class="flex flex-col text-center w-full mb-10">
            <h1 class="sm:text-4xl text-3xl font-medium title-font mb-2 text-gray-900">Crear un nuevo contratista</h1>
            <p class="lg:w-2/3 mx-auto leading-relaxed text-base">Por favor, completa los detalles del contratista a continuación.</p>
        </div>

        {% if messages %}
            <div class="mb-6">
                <ul class="text-red-600">
                    {% for message in messages %}
                        <li>{{ message }}</li>
                    {% endfor %}
                </ul>
            </div>
        {% endif %}

        <form method="POST">
            {% csrf_token %}
            <div class="flex flex-wrap -m-2">
                <!-- Nombre -->
                <div class="p-2 w-full md:w-1/2">
                    <div class="relative">
                        <label for="id_nombre" class="leading-7 text-sm text-gray-600">
                            Nombre del Contratista
                        </label>
                        <input type="text" 
                               id="id_nombre" 
                               name="nombre" 
                               value="{{ form.nombre.value|default:'' }}"
                               required
                               class="w-full bg-gray-100 bg-opacity-50 rounded border border-gray-300 focus:border-indigo-500 focus:bg-white focus:ring-2 focus:ring-indigo-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out">
                    </div>
                </div>

                <!-- NIT o CC -->
                <div class="p-2 w-full md:w-1/2">
                    <div class="relative">
                        <label for="id_nit_o_cc" class="leading-7 text-sm text-gray-600">
                            NIT o Cédula
                        </label>
                        <input type="number" 
                               id="id_nit_o_cc" 
                               name="nit_o_cc"
                               value="{{ form.nit_o_cc.value|default:'' }}"
                               class="w-full bg-gray-100 bg-opacity-50 rounded border border-gray-300 focus:border-indigo-500 focus:bg-white focus:ring-2 focus:ring-indigo-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out">
                    </div>
                </div>

                <!-- Representante Legal -->
                <div class="p-2 w-full md:w-1/2 hidden">
                    <div class="relative">
                        <label for="id_representante_legal" class="leading-7 text-sm text-gray-600">
                            Representante Legal
                        </label>
                        <input type="text" 
                               id="id_representante_legal" 
                               name="representante_legal"
                               value="No aplica"
                               class="w-full bg-gray-100 bg-opacity-50 rounded border border-gray-300 focus:border-indigo-500 focus:bg-white focus:ring-2 focus:ring-indigo-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out">
                    </div>
                </div>

                <!-- NIT o CC Representante Legal -->
                <div class="p-2 w-full md:w-1/2 hidden">
                    <div class="relative">
                        <label for="id_nit_o_cc_representante_legal" class="leading-7 text-sm text-gray-600">
                            NIT o Cédula del Representante Legal
                        </label>
                        <input type="number" 
                               id="id_nit_o_cc_representante_legal" 
                               name="nit_o_cc_representante_legal"
                               value=""
                               class="w-full bg-gray-100 bg-opacity-50 rounded border border-gray-300 focus:border-indigo-500 focus:bg-white focus:ring-2 focus:ring-indigo-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out">
                    </div>
                </div>

                <!-- Teléfono -->
                <div class="p-2 w-full md:w-1/2">
                    <div class="relative">
                        <label for="id_telefono" class="leading-7 text-sm text-gray-600">
                            Teléfono
                        </label>
                        <input type="tel" 
                               id="id_telefono" 
                               name="telefono"
                               value="{{ form.telefono.value|default:'' }}"
                               class="w-full bg-gray-100 bg-opacity-50 rounded border border-gray-300 focus:border-indigo-500 focus:bg-white focus:ring-2 focus:ring-indigo-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out">
                    </div>
                </div>

                <!-- Email -->
                <div class="p-2 w-full md:w-1/2">
                    <div class="relative">
                        <label for="id_email" class="leading-7 text-sm text-gray-600">
                            Correo Electrónico
                        </label>
                        <input type="email" 
                               id="id_email" 
                               name="email"
                               value="{{ form.email.value|default:'' }}"
                               class="w-full bg-gray-100 bg-opacity-50 rounded border border-gray-300 focus:border-indigo-500 focus:bg-white focus:ring-2 focus:ring-indigo-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out">
                    </div>
                </div>

                <!-- Email Secundario -->
                <div class="p-2 w-full md:w-1/2">
                    <div class="relative">
                        <label for="id_email_secundario" class="leading-7 text-sm text-gray-600">
                            Correo Electrónico Secundario
                        </label>
                        <input type="email" 
                               id="id_email_secundario" 
                               name="email_secundario"
                               value="{{ form.email_secundario.value|default:'' }}"
                               class="w-full bg-gray-100 bg-opacity-50 rounded border border-gray-300 focus:border-indigo-500 focus:bg-white focus:ring-2 focus:ring-indigo-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out">
                    </div>
                </div>

                <!-- Consorcio -->
                <div class="p-2 w-full md:w-1/2 hidden">
                    <div class="relative">
                        <label for="id_consorcio" class="leading-7 text-sm text-gray-600">
                            Consorcio
                        </label>
                        <input type="text" 
                               id="id_consorcio" 
                               name="consorcio"
                               value="No aplica"
                               class="w-full bg-gray-100 bg-opacity-50 rounded border border-gray-300 focus:border-indigo-500 focus:bg-white focus:ring-2 focus:ring-indigo-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out">
                    </div>
                </div>
            </div>

            <div class="flex justify-end w-full items-end">
                <div class="p-2 mt-4">
                    <a href="{% url 'sp' %}" class="flex ml-auto text-white bg-red-500 border-0 py-2 px-8 focus:outline-none hover:bg-red-600 rounded text-lg">Cancelar</a>
                </div>
                <div class="p-2 mt-4">
                    <button type="submit" class="flex ml-auto text-white bg-indigo-500 border-0 py-2 px-8 focus:outline-none hover:bg-indigo-600 rounded text-lg">Crear Contratista</button>
                </div>
            </div>
        </form>
    </div>
</section>

{% endblock %}

{% block header %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
{% endblock header %}

{% block scripts %}
<script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
<script src="{% static "js/calendar.js" %}"></script>
{% endblock scripts %}

theme/templates/personal/create_supervisor.html
{% extends "dashboard.html" %}
{% load static tailwind_tags %}
{% load static %}
{% load form_filters %}
{% block title %} SCG - Crear Supervisor {% endblock title %}
{% block contentdash %}

<section class="text-gray-600 body-font w-screen overflow-auto">
    <div class="container px-5 py-14 my-10 ml-10 max-w-[1400px] bg-white shadow-lg rounded-lg">
        <div class="flex flex-col text-center w-full mb-10">
            <h1 class="sm:text-4xl text-3xl font-medium title-font mb-2 text-gray-900">Crear un nuevo supervisor</h1>
            <p class="lg:w-2/3 mx-auto leading-relaxed text-base">Por favor, completa los detalles del supervisor a continuación.</p>
        </div>

        {% if messages %}
            <div class="mb-6">
                <ul class="text-red-600">
                    {% for message in messages %}
                        <li>{{ message }}</li>
                    {% endfor %}
                </ul>
            </div>
        {% endif %}

        <form method="POST" class="w-full mx-auto">
            {% csrf_token %}
            <div class="flex flex-wrap -m-2">
                {% for field in form %}
                    <div class="p-2 w-full md:w-1/2">
                        <div class="relative">
                            <label for="{{ field.id_for_label }}" class="leading-7 text-sm text-gray-600">{{ field.label }}</label>
                            {{ field|add_class:"w-full bg-gray-100 bg-opacity-50 rounded border border-gray-300 focus:border-indigo-500 focus:bg-white focus:ring-2 focus:ring-indigo-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out" }}
                        </div>
                    </div>
                {% endfor %}

                <!-- Botones de Envío y Cancelar -->
                <div class="flex justify-end w-full items-end">
                    <div class="p-2 mt-4">
                        <a href="{% url 'sp' %}" class="flex ml-auto text-white bg-red-500 border-0 py-2 px-8 focus:outline-none hover:bg-red-600 rounded text-lg">Cancelar</a>
                    </div>
                    <div class="p-2 mt-4">
                        <button type="submit" class="flex ml-auto text-white bg-indigo-500 border-0 py-2 px-8 focus:outline-none hover:bg-indigo-600 rounded text-lg">Crear Supervisor</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
</section>

{% endblock %}

{% block header %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
{% endblock header %}

{% block scripts %}
<script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
<script src="{% static "js/calendar.js" %}"></script>
{% endblock scripts %}

theme/templates/personal/tipocontratista.html
{% extends "dashboard.html" %}
{% load static tailwind_tags %}
{% load static %}
{% load form_filters %}
{% block title %} Contratista {% endblock title %}

{% block contentdash %}
<section class="text-gray-600 body-font w-screen overflow-auto">
    <div class="container px-5 py-14 my-10 ml-10 max-w-[1400px] bg-white shadow-lg rounded-lg">
    <div class="flex  items-center justify-center w-full gap-4">
        <a href="{% url 'create-c-pn' %}" class="flex items-center flex-col justify-center text-3xl w-1/4 h-60 py-2 px-4 bg-blue-500 text-white font-bold rounded hover:bg-blue-700 transition duration-300">
            <i class="fa fa-user fa-lg mr-2 mb-10"></i>
            Contratista Personal Natural
        </a>
        <a href="{% url 'create-c' %}" class="flex flex-col items-center justify-center text-3xl w-1/4 h-60 py-2  gap-y-2 px-4 bg-green-500 text-white font-bold rounded hover:bg-green-700 transition duration-300">
            <i class="fa fa-building fa-lg mr-2 mb-10"></i>
            Contratista Persona Jurídica
        </a>
    </div>
    </div>
</section>
{% endblock %}

{% block header %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
{% endblock header %}

{% block scripts %}
<script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
<script src="{% static 'js/calendar.js' %}"></script>
{% endblock scripts %}

theme/templates/personal/update_contratista.html
{% extends "dashboard.html" %}
{% load static tailwind_tags %}
{% load static %}
{% load form_filters %}
{% block title %} Actualizar Contratista {% endblock title %}
{% block contentdash %}

<section class="text-gray-600 body-font w-screen overflow-auto">
    <div class="container px-5 py-14 my-10 bg-white shadow-lg rounded-lg ml-10 max-w-[1400px]">
        <div class="flex flex-col text-center w-full mb-10">
            <h1 class="sm:text-4xl text-3xl font-medium title-font mb-2 text-gray-900">Actualizar Contratista</h1>
            <p class="lg:w-2/3 mx-auto leading-relaxed text-base">Modifica los detalles del contratista a continuación.</p>
        </div>

        <form method="POST" class="w-full mx-auto">
            {% csrf_token %}
            <div class="flex flex-wrap -m-2">
                {% for field in form %}
                    <div class="p-2 w-full md:w-1/2">
                        <div class="relative">
                            <label for="{{ field.id_for_label }}" class="leading-7 text-sm text-gray-600">{{ field.label }}</label>
                            {{ field|add_class:"w-full bg-gray-100 bg-opacity-50 rounded border border-gray-300 focus:border-indigo-500 focus:bg-white focus:ring-2 focus:ring-indigo-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out" }}
                        </div>
                    </div>
                {% endfor %}
                
                <!-- Botones de Envío y Cancelar -->
                <div class="flex justify-end w-full items-end">
                    <div class="p-2 mt-4">
                        <button type="submit" class="flex ml-auto text-white bg-indigo-500 border-0 py-2 px-8 focus:outline-none hover:bg-indigo-600 rounded text-lg">Guardar Cambios</button>
                    </div>
                    
                </div>
                <div class="p-2 mt-4 ml-auto">
                    <a href="{% url 'sp' %}" class="flex ml-auto text-white bg-red-500 border-0 py-1 px-4 focus:outline-none hover:bg-red-600 rounded text-lg">Cancelar</a>
                </div>
            </div>            
        </form>
        {% if request.user.is_superuser %}
            <div class="p-2 mt-4 ">
                <form method="POST" action="{% url 'borrar_contratista' contratista.id %}" onsubmit="return confirm('¿Estás seguro de que deseas eliminar este Contratista?');">
                    {% csrf_token %}
                    <button type="submit" class="bg-red-500 text-white px-4 py-2 rounded">Eliminar Contratista</button>
                </form>
            </div>
        {% endif %}
    </div>
</section>

{% endblock %}